### ISSUE TITLE
 Errors when trying to build a project

### ISSUE THREAD

**Issue by Pavel6778** [bjerkio/unieconomy-js#4]
when to build my project I call the ```tsc``` command
I get such errors
``` Namespace '"http"' has no exported member 'ClientResponse'.```
``` Cannot find name 'ERRORUNKNOWN'.

17746     workrelationsIdactioncalcFlexBalanceGet(id: number, id2: ERRORUNKNOWN): Promise<{
```

I tried changing the version of the node
this did not solve my problem

**Comment by cobraz** [comment]
What version @types/node do you run?

**Comment by Pavel6778** [comment]
```"@types/node": "^12.0.2"```

**Comment by cobraz** [comment]
I will investigate closer. I believe this issue is not caused by this library specifically, but still need to do some cleanup. You are welcome to help out with a PR.

**Comment by hexjelly** [comment]
I don't know if relevant: [https://github.com/swagger-api/swagger-codegen/issues/9168](https://github.com/swagger-api/swagger-codegen/issues/9168)
